using System.Reflection;
using System.Text.Json;
using GAoverlay.Contracts;

namespace GAoverlay.Host.Services;

public sealed class PluginLoader
{
    private readonly string _pluginsRoot;
    private readonly IPluginHost _host;
    private readonly List<(PluginManifest Manifest, IOverlayPlugin? Instance, string Folder, string Status)> _loaded = [];

    public IReadOnlyList<(PluginManifest Manifest, IOverlayPlugin? Instance, string Folder, string Status)> Loaded => _loaded;

    public PluginLoader(string pluginsRoot, IPluginHost host)
    {
        _pluginsRoot = pluginsRoot;
        _host = host;
    }

    public void LoadAll()
    {
        _loaded.Clear();

        if (!Directory.Exists(_pluginsRoot))
        {
            return;
        }

        foreach (var dir in Directory.GetDirectories(_pluginsRoot))
        {
            TryGenerateManifest(dir);
            TryLoadDirectory(dir);
        }
    }

    private void TryGenerateManifest(string dir)
    {
        var manifestPath = Path.Combine(dir, "plugin.json");
        if (File.Exists(manifestPath))
        {
            return;
        }

        var dll = Directory.GetFiles(dir, "*.dll", SearchOption.AllDirectories).FirstOrDefault();
        if (dll is null)
        {
            return;
        }

        try
        {
            var asm = Assembly.LoadFrom(dll);
            var pluginType = asm.GetTypes().FirstOrDefault(t => typeof(IOverlayPlugin).IsAssignableFrom(t) && !t.IsAbstract && !t.IsInterface);
            if (pluginType is null)
            {
                return;
            }

            var instance = Activator.CreateInstance(pluginType) as IOverlayPlugin;
            var folderName = Path.GetFileName(dir);
            var manifest = new PluginManifest
            {
                Id = instance?.Id ?? folderName,
                Name = instance?.Name ?? folderName,
                Author = "Unknown",
                Version = asm.GetName().Version?.ToString() ?? "1.0.0",
                MainAssembly = Path.GetFileName(dll),
                EntryType = pluginType.FullName ?? pluginType.Name,
                Description = $"Auto-generated manifest for {folderName}.",
                Category = "AutoGenerated",
                SettingsFile = $"{folderName}.settings.json",
                EnabledByDefault = true
            };

            File.WriteAllText(manifestPath, JsonSerializer.Serialize(manifest, new JsonSerializerOptions { WriteIndented = true }));
            File.WriteAllText(Path.Combine(dir, "README.txt"), "This plugin manifest was auto-generated because a compatible DLL was found.\n");
        }
        catch (Exception ex)
        {
            _host.Log($"Manifest auto-generation skipped for '{dir}': {ex.Message}");
        }
    }

    private void TryLoadDirectory(string dir)
    {
        try
        {
            var manifestPath = Path.Combine(dir, "plugin.json");
            if (!File.Exists(manifestPath))
            {
                return;
            }

            var manifest = JsonSerializer.Deserialize<PluginManifest>(
                File.ReadAllText(manifestPath),
                new JsonSerializerOptions { PropertyNameCaseInsensitive = true });

            if (manifest is null)
            {
                _loaded.Add((new PluginManifest { Id = Path.GetFileName(dir), Name = Path.GetFileName(dir) }, null, dir, "Manifest parse failed"));
                return;
            }

            var asmPath = ResolveAssemblyPath(dir, manifest.MainAssembly);
            if (asmPath is null)
            {
                _loaded.Add((manifest, null, dir, "Manifest found; assembly not present yet"));
                return;
            }

            var asm = Assembly.LoadFrom(asmPath);
            var type = asm.GetType(manifest.EntryType, throwOnError: false)
                ?? asm.GetTypes().FirstOrDefault(t => typeof(IOverlayPlugin).IsAssignableFrom(t) && !t.IsAbstract && !t.IsInterface);

            if (type is null)
            {
                _loaded.Add((manifest, null, dir, $"Assembly loaded but entry type '{manifest.EntryType}' was not found"));
                return;
            }

            if (Activator.CreateInstance(type) is not IOverlayPlugin instance)
            {
                _loaded.Add((manifest, null, dir, "Entry type did not implement IOverlayPlugin"));
                return;
            }

            instance.Initialize(_host, manifest);
            if (manifest.EnabledByDefault)
            {
                instance.Start();
            }

            _loaded.Add((manifest, instance, dir, "Loaded"));
        }
        catch (Exception ex)
        {
            _loaded.Add((new PluginManifest { Name = Path.GetFileName(dir), Id = Path.GetFileName(dir) }, null, dir, $"Failed: {ex.Message}"));
        }
    }

    private static string? ResolveAssemblyPath(string pluginDir, string mainAssembly)
    {
        if (string.IsNullOrWhiteSpace(mainAssembly))
        {
            return null;
        }

        var directPath = Path.Combine(pluginDir, mainAssembly);
        if (File.Exists(directPath))
        {
            return directPath;
        }

        var dllName = Path.GetFileName(mainAssembly);
        var nested = Directory.GetFiles(pluginDir, dllName, SearchOption.AllDirectories).FirstOrDefault();
        return nested;
    }
}
